### ISSUE TITLE
how to use with ReactiveValueNotifier

### ISSUE THREAD

**Issue by saknarak** [lukehutch/flutter_persistent_value_notifier#1]
I'm new to flutter, your lib is great.

I don't know how to use ReactiveValueNotifier with PersistentValueNotifier

please give me a hint

**Comment by lukehutch** [comment]
They used to work together just fine, because `ReactiveValueNotifier` was an extension on `ValueNotifier` (so the extension could also be used with `PersistentValueNotifier`)... but now they don't work together anymore, because I had to make `ReactiveValueNotifier` subclass `ValueNotifier` to fix a bug ( https://github.com/lukehutch/flutter_reactive_value/issues/5 ).

I would like to get both of them working together again, but I will need to think hard about how to combine these two classes together in a flexible way.

I have a handful of other subclasses of `ValueNotifier` that I developed for my own purposes, such as a `ValueNotifier` that reactively computes a value from the values of other `ValueNotifier`s. I'm thinking about ways of rolling all this together into one super-value-notifier. But I haven't figured it all out yet...

For now, I recommend simply using either `ValueNotifier` or `PersistentValueNotifier` with `ValueListenableBuilder` from Flutter (that's what I typically do these days, I don't use `ReactiveValueNotifier` anymore...).

**Comment by lukehutch** [comment]
... or by the way, you could also use PersistentValueNotifier with `flutter_reactive_value` version `1.0.4` (just don't let it upgrade to `2.0.1`, as long as you understand the (probably typically small) memory leak in the bug I linked above.
